
### Set up Var Names
standard_vars <- c(
	'Events (All or None)' 	  = 'Events+%28+All+or+None+%29',
	'Participant Contacts' 	  = 'Participant+Contacts',
	'Comments Log' 	          = 'Comments+Log',
	'Contact Log' 	          = 'Contact+Log',
	'Email Log' 	            = 'Email+Log',
	'Consent Log' 	          = 'Consent+Log',
	'globalId'                = 'globalId',
	'firstName'               = 'firstName',
	'middleName'              = 'middleName',
	'lastName'                = 'lastName',
	'sex'                     = 'sex',
	'birthday'                = 'birthday',
	'race'                    = 'race',
	'ethnicity'               = 'ethnicity',
	'contactForFutureStudies' = 'contactForFutureStudies',
	'familyId'                = 'familyId',
	'tags'                    = 'tags',
	'dateCreated'             = 'dateCreated',
	'statusId'                = 'statusId',
	'customId'                = 'customId',
	'signedConsentForm'       = 'signedConsentForm',
	'dateSignedConsentForm'   = 'dateSignedConsentForm',
	'age'                     = 'age',
	'lastContactDate'         = 'lastContactDate',
	'strategyId'              = 'strategyId',
	'sourceId'                = 'sourceId',
	'siteId'                  = 'siteId',
	'dateAddedToStudy'        = 'dateAddedToStudy'
)

custom_vars <- c(
	'cv.prenatal_care_clinic',
	'cv.pronouns',
	'cv.latest_roster_update',
	'cv.race_ethnicity_other_than_nh_white',
	'cv.partner_involved_',
	'cv.withdrawn',
	'cv.date_hipaa_consent_completed',
	'cv.due_date',
	'cv.pregnancy_consent_completed',
	'cv.used_sperm_or_egg_donor_',
	'cv.dem_b_needed_',
	'cv.preferred_name',
	'cv.high_risk_pregnancy_',
	'cv.echo_id_from_echo_ppt_reg',
	'cv.last_menstrual_period',
	'cv.preferred_contact_method',
	'cv.consent_date_pregnancy',
	'cv.echo_pin_from_echo_ppt_reg',
	'cv.contact_method_limitations',
	'cv.preferred_language',
	'cv.addr_hx_needed_',
	'cv.echo_ppt_registration_date',
	'cv.special_circumstances'
)
